homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:homePage }

login:
    path:     /login
    defaults: {_controller: FOSUserBundle:Security:login}

addfrais:
    path:     /addfrais
    defaults: {_controller: FrontBundle:Frais:addFrais}


listefrais:
    path:     /listefrais
    defaults: {_controller: FrontBundle:Utilisateur:listefrais}

modifierfrais:
    path:     /modifierfrais
    defaults: {_controller: FrontBundle:Utilisateur:modifierfrais}


addfraistype:
    path:   /admin/addfraistype
    defaults: {_controller: FrontBundle:FraisForfaitType:addFraisForfaitType}

addutilisateur:
    path:   /admin/addutilisateur
    defaults: {_controller: FrontBundle:Admin:addutilisateur}

gererfichesfrais:
    path:   /admin/gererfichesfrais
    defaults: {_controller: FrontBundle:Admin:gererfichesfrais}

listeutilisateur:
    path:   /listeutilisateur
    defaults: {_controller: FrontBundle:user:index}

voirfichefrais:
    path:   /voirfichefrais
    defaults: {_controller: FrontBundle:Admin:voirfichefrais}

user_index:
    path:   /
    defaults: {_controller: FrontBundle:user:index}

user_show:
    path:   /show
    defaults: {_controller: FrontBundle:user:index}