api_connextion:
    path:     /api/connect
    defaults: { _controller: FrontBundle:API:connexionAPI}

api_liste_fiches:
    path:     /api/listefiches/{idUser}
    defaults: { _controller: FrontBundle:API:listeFichesAPI }

api_fiche:
    path:     /api/fiche/{id}
    defaults: { _controller : FrontBundle:API:FicheAPI}

#Home et login
homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:homePage }

login:
    path:     /login
    defaults: {_controller: FOSUserBundle:Security:login}

#Plan du site

plandusite:
    path:   /siteplan
    defaults: {_controller: FrontBundle:Default:siteplan}

# ajoute et suppression de frais niveau utilisateur

addfrais:
    path:     /utilisateur/addfrais
    defaults: {_controller: FrontBundle:Utilisateur:addFrais}

removefraisforfait:
    path:     /utilisateur/{id}/remove
    defaults: {_controller: FrontBundle:Utilisateur:supprimerfraisforfait}

removefraishorsforfait:
    path:     /utilisateur/{id}/remove2
    defaults: {_controller: FrontBundle:Utilisateur:suppfraishorsforfait}

listefrais:
    path:     /utilisateur/listefrais
    defaults: {_controller: FrontBundle:Utilisateur:listefiche}


afficherfichefrais:
    path:   /utilisateur/{id}/afficher
    defaults: {_controller: FrontBundle:Utilisateur:afficherfiche}

modifierfraisforfait:
    path:   /utilisateur/{id}/modifierfrais
    defaults: {_controller: FrontBundle:Utilisateur:modifierfraisforfait}

modifierfraishorsforfait:
    path:   /utilisateur/{id}/modifierfraish
    defaults: {_controller: FrontBundle:Utilisateur:modifierfraishorsforfait}

# Gestion  des fiche de frais par l'admin

voirfichefrais:
    path:   /comptable/{id}/voir
    defaults: {_controller: FrontBundle:Comptable:voirFicheFrais}

supprFiche:
    path:   /comptable/{id}/supprfiche
    defaults: {_controller: FrontBundle:Comptable:supprFicheFrais}

gererfichesfrais:
    path:   /comptable/gererfichesfrais
    defaults: {_controller: FrontBundle:Comptable:gererFiches}


# Validation et refus des frais de la fiche

validerfraisforfait:
    path:   /comptable/{id}/valider
    defaults: {_controller: FrontBundle:Comptable:validerfraisforfait}

refusfraisforfait:
    path:   /comptable/{id}/refuser
    defaults: {_controller: FrontBundle:Comptable:refuserfraisforfait}

validerfraishorsforfait:
    path:   /comptable/{id}/valider
    defaults: {_controller: FrontBundle:Comptable:validerfraishorsforfait}

refusfraishorsforfait:
    path:   /comptable/{id}/refuser
    defaults: {_controller: FrontBundle:Comptable:refuserfraishorsforfait}


# Ajout et gestion de fraistype par l'admin

addfraistype:
    path:   /admin/addfraistype
    defaults: {_controller: FrontBundle:Admin:addFraisForfaitType}

removefraistype:
    path:   /admin/{id}/removeft
    defaults: {_controller: FrontBundle:Admin:removeFraisType}


modifierfraistype:
    path:   /admin/{id}/modifierft
    defaults: {_controller: FrontBundle:Admin:modifierFraisType}

# Ajoute et gestion des des utilisateur par l'admin

addutilisateur:
    path:   /admin/addutilisateur
    defaults: {_controller: FrontBundle:Admin:addutilisateur}

listeutilisateur:
    path:   /admin/listeutilisateur
    defaults: {_controller: FrontBundle:Admin:listeuser}

user_edit:
    path:   /admin/user/{id}/edit
    defaults: {_controller: FrontBundle:Admin:modifieruser }

user_remove:
    path:   /admin/user/{id}/remove
    defaults: {_controller: FrontBundle:Admin:supprimeruser }
