#Home et login
homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:homePage }

login:
    path:     /login
    defaults: {_controller: FOSUserBundle:Security:login}

#Plan du site

plandusite:
    path:   /siteplan
    defaults: {_controller: FrontBundle:Default:siteplan}

# ajoute et suppression de frais niveau utilisateur

addfrais:
    path:     /addfrais
    defaults: {_controller: FrontBundle:Frais:addFrais}

removefraisforfait:
    path:     /frais/{id}/remove
    defaults: {_controller: FrontBundle:Frais:supprimerfraisforfait}

removefraishorsforfait:
    path:     /frais/{id}/remove2
    defaults: {_controller: FrontBundle:Frais:suppfraishorsforfait}

voirfichefrais:
    path:   /fichefrais/{id}/voir
    defaults: {_controller: FrontBundle:FicheFrais:voirFicheFrais}

afficherfichefrais:
    path:   /fichefrais/{id}/afficher
    defaults: {_controller: FrontBundle:FicheFrais:afficherfiche}

modifierfraisforfait:
    path:   /fiche/fichefrais/{id}/modifierfrais
    defaults: {_controller: FrontBundle:FicheFrais:modifierfraisforfait}

modifierfraishorsforfait:
    path:   /fiche/fichefrais/{id}/modifierfraish
    defaults: {_controller: FrontBundle:FicheFrais:modifierfraishorsforfait}

# Gestion  des fiche de frais par l'admin

listefrais:
    path:     /listefrais
    defaults: {_controller: FrontBundle:FicheFrais:listefiche}

supprFiche:
    path:     /admin/{id}/supprfiche
    defaults: {_controller: FrontBundle:FicheFrais:supprFicheFrais}

gererfichesfrais:
    path:   /admin/gererfichesfrais
    defaults: {_controller: FrontBundle:FicheFrais:gererFiches}


# Validation et refus des frais de la fiche

validerfraisforfait:
    path:   /fraisforfait/{id}/valider
    defaults: {_controller: FrontBundle:Frais:validerfraisforfait}

refusfraisforfait:
    path:   /fraisforfait/{id}/refuser
    defaults: {_controller: FrontBundle:Frais:refuserfraisforfait}

validerfraishorsforfait:
    path:   /fraishorsforfait/{id}/valider
    defaults: {_controller: FrontBundle:Frais:validerfraishorsforfait}

refusfraishorsforfait:
    path:   /fraishorsforfait/{id}/refuser
    defaults: {_controller: FrontBundle:Frais:refuserfraishorsforfait}


# Ajout et gestion de fraistype par l'admin

addfraistype:
    path:   /admin/addfraistype
    defaults: {_controller: FrontBundle:FraisForfaitType:addFraisForfaitType}

removefraistype:
    path:   /admin/{id}/removeft
    defaults: {_controller: FrontBundle:FraisForfaitType:removeFraisType}

# Ajoute et gestion des des utilisateur par l'admin

addutilisateur:
    path:   /admin/addutilisateur
    defaults: {_controller: FrontBundle:Admin:addutilisateur}

listeutilisateur:
    path:   /admin/listeutilisateur
    defaults: {_controller: FrontBundle:Admin:listeuser}

user_edit:
    path:   /user/{id}/edit
    defaults: {_controller: FrontBundle:Admin:modifieruser }

user_remove:
    path:   /user/{id}/remove
    defaults: {_controller: FrontBundle:Admin:supprimeruser }
