homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:homePage }

login:
    path:     /login
    defaults: {_controller: FOSUserBundle:Security:login}

addfrais:
    path:     /addfrais
    defaults: {_controller: FrontBundle:Frais:addFrais}


listefrais:
    path:     /listefrais
    defaults: {_controller: FrontBundle:Utilisateur:listefrais}

modifierfrais:
    path:     /modifierfrais
    defaults: {_controller: FrontBundle:Utilisateur:modifierfrais}


addfraistype:
    path:   /admin/addfraistype
    defaults: {_controller: FrontBundle:FraisForfaitType:addFraisForfaitType}

addutilisateur:
    path:   /admin/addutilisateur
    defaults: {_controller: FrontBundle:Admin:addutilisateur}

listeutilisateur:
    path:   /admin/listeutilisateur
    defaults: {_controller: FrontBundle:Admin:listeuser}

gererfichesfrais:
    path:   /admin/gererfichesfrais
    defaults: {_controller: FrontBundle:FicheFrais:gererFiches}

voirfichefrais:
    path:   /admin/voirfichefrais
    defaults: {_controller: FrontBundle:Admin:voirfichefrais}


user_edit:
    path:   /user/{id}/edit
    defaults: {_controller: FrontBundle:Admin:modifieruser }

user_remove:
    path:   /user/{id}/remove
    defaults: {_controller: FrontBundle:Admin:supprimeruser }
