front_fiche_frais:
    resource: "@FrontBundle/Controller/FicheFraisController.php"
    type:     annotation


front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"