<?php

namespace FrontBundle\Repository;

/**
 * EtatFicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatFicheRepository extends \Doctrine\ORM\EntityRepository
{
}
