<?php

namespace FrontBundle\Repository;

/**
 * FraisHorsForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisHorsForfaitRepository extends \Doctrine\ORM\EntityRepository
{
}
