<?php

namespace FrontBundle\Repository;

/**
 * FraisForfaitTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraisForfaitTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
